{"uuid": "8139ffc6-c171-4d04-8ec0-5007fb48fb74", "children": ["463dabcd-1291-466f-88a0-7425dc621cc6", "27feb064-45de-422b-9494-97df20af240b", "abb4a459-27f0-42bb-97c0-350946b9c2fe", "bfecf1a5-b078-47af-8df0-553b6a2f3450", "5ced7bd6-1424-4631-b5e3-4f3512b2d78d", "413a5669-c6f3-4c7e-bdd9-36522a293826"], "befores": [{"name": "preprod_setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=138.0.7204.185)\nStacktrace:\n\tGetHandleVerifier [0x0x7ff625b5e415+77285]\n\tGetHandleVerifier [0x0x7ff625b5e470+77376]\n\t(No symbol) [0x0x7ff625929a6a]\n\t(No symbol) [0x0x7ff625901f21]\n\t(No symbol) [0x0x7ff6259af9be]\n\t(No symbol) [0x0x7ff6259d0192]\n\t(No symbol) [0x0x7ff6259a83e3]\n\t(No symbol) [0x0x7ff625971521]\n\t(No symbol) [0x0x7ff6259722b3]\n\tGetHandleVerifier [0x0x7ff625e41efd+3107021]\n\tGetHandleVerifier [0x0x7ff625e3c29d+3083373]\n\tGetHandleVerifier [0x0x7ff625e5bedd+3213485]\n\tGetHandleVerifier [0x0x7ff625b7884e+184862]\n\tGetHandleVerifier [0x0x7ff625b8055f+216879]\n\tGetHandleVerifier [0x0x7ff625b67084+113236]\n\tGetHandleVerifier [0x0x7ff625b67239+113673]\n\tGetHandleVerifier [0x0x7ff625b4e298+11368]\n\tBaseThreadInitThunk [0x0x7fffbc0d7374+20]\n\tRtlUserThreadStart [0x0x7fffbdd5cc91+33]\n\n", "trace": "  File \"C:\\Users\\gaurav\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\gaurav\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\gaurav\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\gaurav\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\gaurav\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\gaurav\\Desktop\\iFOLIO\\Automation\\ifolio_preprod\\testcases\\preprod_testcases\\conftest.py\", line 35, in preprod_setup\n    lp.enter_email(preprod_test_data['email'])\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\gaurav\\Desktop\\iFOLIO\\Automation\\ifolio_preprod\\pageObject\\preprod\\Login_Page.py\", line 19, in enter_email\n    self.driver.find_element(*Login.Email_xpath).send_keys(email)\n    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\gaurav\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 770, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\gaurav\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 384, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"C:\\Users\\gaurav\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1754993212373, "stop": 1754993215149}], "afters": [{"name": "preprod_setup::quit", "status": "broken", "statusDetails": {"message": "KeyboardInterrupt\n", "trace": "  File \"C:\\Users\\gaurav\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\allure_commons\\_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\gaurav\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 193, in quit\n    self.service.stop()\n    ~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\gaurav\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 152, in stop\n    self.send_remote_shutdown_command()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\gaurav\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 137, in send_remote_shutdown_command\n    if not self.is_connectable():\n           ~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\gaurav\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 126, in is_connectable\n    return utils.is_connectable(self.port)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"C:\\Users\\gaurav\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\common\\utils.py\", line 101, in is_connectable\n    socket_ = socket.create_connection((host, port), 1)\n  File \"C:\\Users\\gaurav\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\socket.py\", line 856, in create_connection\n    exceptions.clear()  # raise only the last error\n    ~~~~~~~~~~~~~~~~^^\n"}, "start": 1754993215739, "stop": 1754993218071}], "start": 1754993212373, "stop": 1754993218072}